[tool.poetry]
name = "server"
version = "0.1.0"
description = "Server for the Tabby app."
authors = ["Ederic Oytas <edericoytas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.3"
requests = "^2.32.3"
python-dotenv = "^1.0.1"
google-api-python-client = "^2.149.0"
google-cloud = "^0.34.0"
google-cloud-vision = "^3.7.4"


[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.1"
pytest = "^8.3.3"
pytest-cov = "^5.0.0"
requests-mock = "^1.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
log_cli = 1
log_file = "logs/pytest.log"
log_file_level = "INFO"
